### ISSUE TITLE
Deployers (create mod 1.16.5)

### ISSUE THREAD

**Issue by TheVirusUk** [ClaudiusMinimus/Ninety-Nine-Mods-on-the-Wall-1.16.4#2]
After several crashes we beleive the issue at hand was that, the deployers when empty handed poked a sapling this would cause the crash. If the deployers is holding an item (bone meal) it did not seem to crash from initial testing.

**Comment by ClaudiusMinimus** [comment]
This issue has been fixed with version 1.16.5-1.7.1
