### ISSUE TITLE
Unabled to sort improved backpacks while cyclic ender lead is inside

### ISSUE THREAD

**Issue by Jactin** [ClaudiusMinimus/Ninety-Nine-Mods-on-the-Wall-1.16.4#3]
The sort button and the middle mouse sort key do not work for improved backpacks while there is an ender lead from cyclic placed inside.   Attempting to do so will place the ender lead into the mouse cursor. If repeated too many times, the client will crash.

Likely conflicting mods:
cyclic
improved backpacks

Secondary mods:
whichever two are currently used to sort inventory

**Comment by Jactin** [comment]
Addendum:   same happens with sorting general inventory with cyclic ender lead in general inventory

**Comment by ClaudiusMinimus** [comment]
Can you provide a links to latest.log and crash-report using a service like [pastebin](https://pastebin.com/)?
