### ISSUE TITLE
Packing Tape dupe/delete

### ISSUE THREAD

**Issue by Jactin** [ClaudiusMinimus/Ninety-Nine-Mods-on-the-Wall-1.16.4#4]
Whilst using packing tape on double chests (vanilla). After unpacking, if chests are placed apart, the contents of one chest are duplicated whilst whatever was in the other side is deleted.  Additionally, I noticed that adjacent chests (the ones stacked above the duped chest)  were ALSO duped to the first chest whilst their contents were deleted.

**Comment by ClaudiusMinimus** [comment]
Thank you I will forward this to the devs

**Comment by ClaudiusMinimus** [comment]
Can you provide a link to latest.log using a service like [pastebin](https://pastebin.com/)?
