### ISSUE TITLE
Create Mod - Mechanical Crafter vs gold nugget

### ISSUE THREAD

**Issue by Jactin** [ClaudiusMinimus/Ninety-Nine-Mods-on-the-Wall-1.16.4#5]
Unable to create the Rotation Speed Controller from Create.

Placing all items EXCEPT the gold nugget into the mechanical crafter work fine.  However, placing gold nuggets renders an error message who's log is only viewable server side.

**Comment by ClaudiusMinimus** [comment]
Can you provide a link to latest.log using a service like [pastebin](https://pastebin.com/)?

**Comment by ClaudiusMinimus** [comment]
Has been fixed
