### ISSUE TITLE
Game crashes while in server 

### ISSUE THREAD

**Issue by twistedgamersfm** [ClaudiusMinimus/Ninety-Nine-Mods-on-the-Wall-1.16.4#7]
When I join the server I am lagging a lot and I crash I don’t know why I’m crashing when it works fine on most other servers besides one

**Comment by ClaudiusMinimus** [comment]
In order to help you I need the following:

1. crash report
2. latest.log for the crash. 
3. Pack version number

**Comment by twistedgamersfm** [comment]
[latest.log](https://github.com/ClaudiusMinimus/Ninety-Nine-Mods-on-the-Wall-1.16.4/files/6551228/latest.log)
no crash report because it just closes my acess from the server and pack verison is the latest update

**Comment by twistedgamersfm** [comment]
[latest.log](https://github.com/ClaudiusMinimus/Ninety-Nine-Mods-on-the-Wall-1.16.4/files/6551238/latest.log)

**Comment by twistedgamersfm** [comment]
did not mean to close

**Comment by ClaudiusMinimus** [comment]
I do not see anything in the logs that might have caused the crash - though I am no expert when it comes to crash logs.
What are the specs of your PC?
CPU:
GPU:
OS:
Total RAM:
Allocated RAM to pack:
